# Configuración para Netlify

[build]
  # Comando para construir tanto el backend como el frontend
  command = "npm ci --legacy-peer-deps && cd backend && npm ci --legacy-peer-deps && npm run build && cd ../smartshop-frontend && npm ci --legacy-peer-deps && npm run build"
  
  # Directorio del frontend que se va a publicar
  publish = "smartshop-frontend/dist"
  
  # Directorio donde Netlify buscará las funciones serverless
  # Apuntamos directamente al directorio de salida del backend
  functions = "backend/dist"

# Variables de entorno para el build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--legacy-peer-deps"
  # Variables para el frontend
  VITE_API_URL = "/.netlify/functions"

# Redirección para la API para que apunte a la función serverless principal
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat" # 'index' es el nombre del archivo de entrada (index.js)
  status = 200

# Redirección para la Single Page Application (SPA) de React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para archivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para archivos JS y CSS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
